puts: Return EOF on error
phoenix-rtos/libphoenix pull request #264
Opened 2023-06-20 10:29 UTC by agkaminski

DONE: RTOS-503

## Description

Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/260

## Motivation and Context

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-06-20 12:09 UTC, damianloew submitted a review, later dismissed
LGTM

2023-06-20 14:21 UTC, badochov requested changes

2023-06-20 14:21 UTC, badochov commented on stdio/file.c
> +	return (int)len;
`len > MAX_INT ? MAX_INT : len`

2023-06-20 14:21 UTC, badochov commented on stdio/file.c
> +	if (fwrite_unlocked(s, 1, len, stream) != len) {
I think the write should be retried until either len bytes is written or error is encoutered

2023-06-20 15:11 UTC, badochov approved these changes
LGTM, maybe `puts_unlocked` should use this function to simplify the code a little bit

2023-07-03 08:43 UTC, agkaminski commented
I don't think my change is causing `host-generic-pc` target to fail - it does not even use this code

2023-07-03 14:38 UTC, damianloew commented
> I don't think my change is causing `host-generic-pc` target to fail - it does not even use this code

There was a failed build on nucleo (before splitting test-libc) caused by some GH problems (The hosted runner: GitHub Actions 9 lost communication with the server) and after some time you probably clicked `re-run failed jobs`, but during this period splitting test-libc binary has been merged and the previous builds were used (without test-libc-pthread binary). Clicking `re-run all jobs` triggered by @mateusz-bloch finally helped. So it seems to be fine as we can see in `checks` tab now.

2023-07-21 12:00 UTC, badochov submitted a review, later dismissed

2023-07-21 12:02 UTC, agkaminski commented on stdio/file.c
> +		ret = fwrite_unlocked(s + wrote, 1, len - wrote, stream);
Right, now it should be ok, thanks

2023-07-21 12:05 UTC, badochov commented on stdio/file.c
> +	while (wrote < len) {
What do you think about using `for` here?

2023-07-21 12:12 UTC, badochov approved these changes

2023-07-25 06:30 UTC, merged