string: strerror_r() implementation
phoenix-rtos/libphoenix pull request #280
Opened 2023-08-10 12:44 UTC by agkaminski

DONE: RTOS-554

## Description

Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/694

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (ia32-generic-qemu).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-08-10 13:37 UTC, mateusz-bloch reviewed
LGTM, checked strerror_r on emu and hardware targets

2023-08-10 18:19 UTC, badochov requested changes
`strerror` should only have race with itself, but in current implementation there's a race between `strerror` and `gai_strerror`, I'd make `err_unknownMsg`  a static variable inside each of this functions

2023-08-10 19:04 UTC, kemonats commented on string/strerror.c
> +	int err;
initialization of the err variable is missing
```suggestion
	int err = 0;
```

2023-08-11 10:35 UTC, badochov commented
I've never seen those failures on imxrt117 before however the code seems valid

2023-08-11 10:43 UTC, agkaminski commented
> I've never seen those failures on imxrt117 before however the code seems valid

Random fail yet again

2023-08-11 10:44 UTC, badochov approved these changes
LGTM

2023-08-11 11:46 UTC, merged